export const text = {
  English: {
    welcome: "Welcome!",
    signupUserTaken: "Sorry, username is already taken!",
    signupNameTaken: "Sorry, name is already taken!",
    signupError: "Sorry, there was an error somehow. Try again?",
    signupShortPW: "Password must be at least 6 characters long!",
    signupUnmatchedPW: "Passwords do not match!",
    signupNewUser: "Create New User",
    signupSuccess: "New user created successfully!",
    name: "Name:",
    username: "Username:",
    password: "Password:",
    confirmPassword: "Confirm Password:",
    signupCreate: "Create User",
    login: "Login",
    signup: "Sign up",
    logout: "Logout",
    greet: "Hello",
    loginFail: "Invalid userid or password. If you do not have an account, please sign up for one.",
    role: "Role:",
    link: "Restricted webpage",
  },
  
  简体中文: {
    welcome: "欢迎！",
    signupUserTaken: "不好意思，用户名已被占用！",
    signupNameTaken: "不好意思， 名称已被占用！",
    signupError: "不好意思，登录失败。再试一试？",
    signupShortPW: "密码必须至少6个字符!",
    signupUnmatchedPW: "密码不匹配!",
    signupNewUser: "创建新用户",
    signupSuccess: "成功创建新用户!",
    name: "名称:",
    username: "用户名:",
    password: "密码:",
    confirmPassword: "确认密码:",
    signupCreate: "创建用户",
    login: "登录",
    signup: "注册",
    logout: "登出",
    greet: "你好",
    loginFail: "无效的用户名或密码。如果没有帐户，请注册一个。",
    role: "角色:",
    link: "受限制的网页",
  },
  繁体中文: {
    welcome: "歡迎！",
    signupUserTaken: "不好意思，用戶名已被佔用！",
    signupNameTaken: "不好意思，名稱已被佔用！ ",
    signupError: "不好意思，登錄失敗。再試一試?",
    signupShortPW: "密碼必須至少6個字符! ",
    signupUnmatchedPW: "密碼不匹配!",
    signupNewUser: "創建新用戶",
    signupSuccess: "成功創建新用戶!",
    name: "名稱:",
    username: "用戶名:",
    password: "密碼:",
    confirmPassword: "確認密碼:",
    signupCreate: "創建用戶",
    login: "登錄",
    signup: "註冊",
    logout: "登出",
    greet: "你好",
    loginFail: "無效的用戶名或密碼。如果沒有帳戶，請註冊一個。",
    role: "角色:",
    link: "受限制的網頁",
  },
  日本語: {
    welcome: "いっらしゃい！",
    signupUserTaken: "申し訳ありません、このユーザー名はすでに使用されています。",
    signupNameTaken: "申し訳ありません、この名前はすでに使用されています。",
    signupError: "申し訳ありませんが、エラーが発生しました。もう一度やり直してください。",
    signupShortPW: "パスワードは6文字以上にしてください。",
    signupUnmatchedPW: "パスワードが一致していません。",
    signupNewUser: "新しいユーザーを作成する",
    signupSuccess: "新しいユーザーが作成しました。",
    name: "名前:",
    username: "ユーザー名:",
    password: "パスワード:",
    confirmPassword: "パスワード認証:",
    signupCreate: "ユーザーを作成する",
    login: "ログイン",
    signup: "登録（とうろく）",
    logout: "ログアウト",
    greet: "こんにちわ",
    loginFail: "無効なユーザーID、パスワード。 アカウントをお持ちでない場合は、登録してください。",
    role: "役:",
    link: "アクセス制限",
  },
};